[package]
edition = "2021"
name = "platform_napi"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
napi = { version = "2.11.2", features = ["napi8"] }
napi-derive = "2.11.1"
bitflags = "1.3.2"
lazy_static = "1.4.0"

[target.'cfg(target_os = "linux")'.dependencies]
x11-dl = { version = "2.18.5", optional = true }

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.44.0"
features = [
  "Win32_Foundation", 
  "Win32_UI_Input", 
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_System_Threading",
  "Win32_System_Shutdown",
  "Win32_Graphics_Gdi"
]

[build-dependencies]
napi-build = "2.0.1"
cfg_aliases = "0.1.1"
