[package]
edition = "2021"
name = "platform_napi"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.10.14", features = ["full"] }
napi-derive = "2.10.1"
lazy_static = "1.4.0"

[target.'cfg(windows)'.dependencies]
windows = {  version = "0.44.0", features = ["Win32_Foundation","Win32_System_LibraryLoader","Win32_UI_WindowsAndMessaging","Win32_UI_Shell","Win32_System_Memory","Win32_UI_Controls","Win32_System_Threading","Win32_System_Diagnostics_Debug","Win32_Graphics_Gdi","Win32_Graphics_Dwm","Win32_System_Shutdown" ] }
wchar = "0.11.0"

# [target.'cfg(not(windows))'.dependencies]
# device_query = { version = "1.1.2", features = [] }

# [target.'cfg(linux)'.dependencies]
# x11 = "2.21.0"
# wayland-client = "0.30.0"

[build-dependencies]
napi-build = "2.0.1"
