[package]
edition = "2021"
name = "platform_napi"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
napi = { version = "2.16.4", features = ["napi8"] }
napi-derive = "2.16.3"
bitflags = "2.5.0"
lazy_static = "1.4.0"
os_info = "3.8.2"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
rdev = "0.5.3"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.56.0"
features = [
  "Win32_Foundation",
  "Win32_UI_Shell",
  "Win32_UI_Input", 
  "Win32_System_LibraryLoader",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_System_Threading",
  "Win32_System_Shutdown",
  "Win32_Graphics_Gdi"
]

[build-dependencies]
napi-build = "2.1.3"
cfg_aliases = "0.2.0"
