/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function setMainWindowHandle(bigint: bigint): void
export function insertWndProcHook(callback: (...args: any[]) => any): void
export function removeWndProcHook(): boolean
export function acquireShutdownBlock(reason: string): boolean
export function releaseShutdownBlock(): boolean
