/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum RawEvent {
  KeyDown = 0,
  KeyUp = 1,
  MouseDown = 2,
  MouseUp = 3,
  MouseMove = 4,
  MouseWheel = 5,
  UnKnown = 6
}
export interface InputEvent {
  kind: RawEvent
  x: number
  y: number
  scancode: number
  virtualKeycode: number
  delta: number
  modifiers: number
}
export function setupInteractiveWindow(window: BigInt, callback?: (err: null | Error, event: InputEvent) => void): void
export function getDesktopIconVisibility(): boolean
export function setDesktopIconVisibility(isVisible: boolean): void
export function isDesktop(): boolean
export function restoreInteractiveWindow(): void
export function setMainWindowHandle(bigint: bigint): void
export function insertWndProcHook(callback: (...args: any[]) => any): void
export function removeWndProcHook(): boolean
export function acquireShutdownBlock(reason: string): boolean
export function releaseShutdownBlock(): boolean
